ALTER TABLE tickets ADD COLUMN project_key TEXT NOT NULL DEFAULT '';
ALTER TABLE ideas ADD COLUMN project_key TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN project_key TEXT NOT NULL DEFAULT '';
ALTER TABLE todays_plan ADD COLUMN project_key TEXT NOT NULL DEFAULT '';
ALTER TABLE social_posts ADD COLUMN project_key TEXT NOT NULL DEFAULT '';
ALTER TABLE action_plan_items ADD COLUMN project_key TEXT NOT NULL DEFAULT '';
ALTER TABLE content_requests ADD COLUMN project_key TEXT NOT NULL DEFAULT '';
ALTER TABLE website_updates ADD COLUMN project_key TEXT NOT NULL DEFAULT '';
ALTER TABLE changelog ADD COLUMN project_key TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS daily_reports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  report_date TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  wins TEXT NOT NULL DEFAULT '',
  blockers TEXT NOT NULL DEFAULT '',
  updated_by TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
