name = "fenster-lead-email"
main = "src/index.js"
compatibility_date = "2026-06-03"
workers_dev = true

[vars]
LEAD_EMAIL_FROM = "fenster-leads@hydronapplications.co.uk"
LEAD_EMAIL_TO = "info@fensterglazing.com"
